### ISSUE TITLE
Keep service running after closing from app switcher

### ISSUE THREAD

**Issue by m1ga** [benbahrenburg/benCoding.AlarmManager#30]
Hi,
I've added a alarm service like this:

alarmManager.addAlarmService({
    requestCode : 10, service : 'com.dev.app.ServiceService', minute : now.getMinutes(), second : 30, interval : 1000 \* 60 \* 5
});

Which is working when the app is running or when I close the app with the back button. But as soon as I remove it from the app switcher it stops working. Inside "Settings - Apps - Running" I see "process 0 / service 1" but it won't run. Is there a way to keep it running even if I close it from the switcher?

**Comment by deckameron** [comment]
@benbahrenburg Do you have a example of a never ending background service in Titanium Android?
I have tried using the standard one from the docs, but as soon as I close the app (swiping it away), the process stops. Could you please assist us?
