### ISSUE TITLE
Notification stops after close mobile device and open it again or reboot the phone

### ISSUE THREAD

**Issue by MahmoudElmoghazy** [benbahrenburg/benCoding.AlarmManager#50]
hi now i have a problem when i close the mobile device or reboot the mobile the notfication stops and to open it again i have to open the application again i think i need a permission to do this can u help me

**Comment by AppWerft** [comment]
+1 I have the same problem. In my app I want the get new feeds from server after midnight. It works, but after reboot I don't see locale notifications triggered by service.

**Comment by farwayer** [comment]
Use benCoding.Android.Tools for registering BootReceiver and reactivate alarms after device reboot.

**Comment by AppWerft** [comment]
Thanks, I will looking for. I don't understand all, but I guess with this special entries in manifest the app will restarted without activity (?) In app.js I have inserted a code https://github.com/AppWerft/DLRmediathek/blob/master/Resources/app.js#L38-L39  to require a module which starts alarmManger (https://github.com/AppWerft/DLRmediathek/blob/master/Resources/vendor/cronservice.trigger.js). I hope this is the right way.
