### ISSUE TITLE
Triggering app start with parameter?

### ISSUE THREAD

**Issue by AppWerft** [benbahrenburg/benCoding.AlarmManager#52]
Hi Ben,
you module works awesome. My question: In the tray comes my message. Now I'm looking for a way the start the app with a parameter to "link" a special "page". Is it possible?

**Comment by benbahrenburg** [comment]
You would need to fork the code and add the ability to pass more information to the launch intent. Then you would need to get that intent information on the Ti side.  If that is to much, you could always fork the code and write a property in the module, then read that property on launch in Ti.  Although not as clean, it is an easier approach.
