### ISSUE TITLE
Parameters (arguments for   Alarmservice

### ISSUE THREAD

**Issue by AppWerft** [benbahrenburg/benCoding.AlarmManager#53]
Hello Ben,
my goal: downloading of big files in background. 
Idea: click on list triggered this method
https://github.com/AppWerft/DLRmediathek/blob/master/Resources/controls/feed.adapter.js#L44-L52
And now I ask me, how I can read url in service process. Do you have an idea?

Rainer

**Comment by benbahrenburg** [comment]
Rainer, I wouldn't do this via the AlarmManager, this sounds like something you should be doing via an Android service which is run via an interval  http://docs.appcelerator.com/titanium/latest/#!/api/Titanium.Android.Service

**Comment by AppWerft** [comment]
Thanks.
