### ISSUE TITLE
Catch event when notification is clicked in drawer

### ISSUE THREAD

**Issue by KKUranium** [benbahrenburg/benCoding.AlarmManager#57]
I want to catch the event when notification is clicked in drawer so that I can open notification screen in my app to show notification.

**Comment by benbahrenburg** [comment]
This module doesn't allow for this.  You can always implement and send a PR.

**Comment by KKUranium** [comment]
What is PR?
Can you explain in detail. Please

**Comment by benbahrenburg** [comment]
PR is short for pull request.  Usually this entails you forking the code, making the updates and then sending a pull request. Here is a "how to" guide that provides more specific details https://help.github.com/articles/using-pull-requests/
