### ISSUE TITLE
how to actually cancel all alarms? cancelNotifications doesn't work as I expect

### ISSUE THREAD

**Issue by beaurushton** [benbahrenburg/benCoding.AlarmManager#68]
Edit: original post edited as cancelAlarmNotification seems to work as expected however cancelNotifications doesn't.

Is there a way to cancel all alarms at once?  Or must I keep a record of all request codes and cancel them individually.  cancelNotifications method doesn't cancel future notifications only clears the status bar.

**Comment by benbahrenburg** [comment]
If you are using request codes, you will need to cancel them individually.  You can always fork the code and implement a different solution for yourself.

**Comment by beaurushton** [comment]
So basically the answer is no :)
