### ISSUE TITLE
Custom sound not playing

### ISSUE THREAD

**Issue by michielvaneerd** [benbahrenburg/benCoding.AlarmManager#85]
The DEFAULT_SOUND flag is always set when a custom sound is specified. According to the Android docs: "This will ignore any given sound." so the custom sound is not playing. I created a pull request https://github.com/benbahrenburg/benCoding.AlarmManager/pull/84 to fix this.

**Comment by michielvaneerd** [comment]
Resolved nu last merge

**Comment by Astrovic** [comment]
Hi @michielvaneerd, the audio file must have a precise extension? 
I have an .aif file in the `/platform/android/res/raw/sound.aif` folder and add it using 

```
alarmManager.addAlarmNotification({
	// other properties...
	playSound: false,
	sound: Ti.Filesystem.getResRawDirectory() + "sound"
});
```

but no sound is playing.

**Comment by michielvaneerd** [comment]
I'm not able to test it, but I think you have to set playSound to true *and* specify your custom sound:

```
alarmManager.addAlarmNotification({
	// other properties...
	playSound: true,
	sound: Ti.Filesystem.getResRawDirectory() + "sound"
});
```

**Comment by Astrovic** [comment]
If I set playSound:true notification uses the default sound

**Comment by michielvaneerd** [comment]
I'm sure you have to set playSound to true and set a valid path to a sound file, so including the extension (sound.aif). I don't know if .aif is a valid extensions though, so you may test with .wav or .mp3.

**Comment by Astrovic** [comment]
OK thanks, I'll try using .mp3 or .wav files.

**Comment by Astrovic** [comment]
Ok, using .mp3 and `playSound: true` it works, and you can use sounds located in `/assets` folder too
