### ISSUE TITLE
bencoding.alarmmanager module 0.16  version greyed out and apiversion is 23 in manifest

### ISSUE THREAD

**Issue by simbu-anubavam** [benbahrenburg/benCoding.AlarmManager#86]
Hi,
I could not see the module in tiapp.xml Overview. Its greyed out, Can you help me to resolve this issue. I'm using Ti SDK 5.5.0 GA, so i m using the bencoding.alarmmanager module 0.16 ( 2016-07-14 20:41:13). 

Note: 
I've noticed the manifest is having apiversion is 23, but it should be 2 i think, after changing that the module is showing, But the Notification is not showing

**Comment by benbahrenburg** [comment]
Hi @simbu-anubavam you simply need to download and build from source.

**Comment by simbu-anubavam** [comment]
Hi @benbahrenburg  
 I've  Build the module from the source, But that also not showing the notification

**Comment by benbahrenburg** [comment]
@simbu-anubavam you'll need to update the api version in the manifest file and dependencies ie Ti jar files.
